# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webD', '0004_allarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allarticles',
            name='Link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='allarticles',
            name='Name',
            field=models.CharField(max_length=500),
        ),
    ]
